		<div class="t-innerWrap">
			<form action="/answer/do/do/edit" method="POST" accept-charset="utf-8" >
				<table>
					<tr>
						<td>
							<label for="l-username">修改回复内容:</label>
						</td>
						<td>
							<textarea name="info[content]" id="add_answer_content" rows="3" cols="50"></textarea>
						</td>
					</tr>
					<tr>
						<td>&nbsp;</td>
						<td>
							<input type="hidden" value="<?=$this->id?>" name="info[id]" >
							<span><input type="submit" value="提交" class="t-submit"/></span>
							<span><input type="button" value="取消" class="t-submit" onclick="cannelShow()"/></span>
						</td>
					</tr>
				</table>
			</form>
	</div>		