<?php
//$cache_key = sprintf('%s|%s|%s_%s', 'ask', 'disease_'.$this->status, $this->classid, $this->page_now==''?'0':$this->page_now);
//$data = QLib_Cache_Client::getPageCache('pages', $cache_key,24);
//if ($data) {
//    echo $data;
//} else {
//    ob_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php echo $this->title;?></title>
<meta name="Keywords" content="<?php echo $this->keywords;?>" />
<meta name="description" content="<?php echo $this->description;?>" />
<link rel="stylesheet" type="text/css" href="/ask/v1/css/main.css?v=20160810">
<link rel="stylesheet" type="text/css" href="/ask/v1/css/rclumn.css?v=20160805_01">
<link rel="stylesheet" type="text/css" href="/ask/v1/css/disease.css?v=20151203_07">
<link rel="stylesheet" type="text/css" href="/ask/v1/css/bd_search.css?v=20151203_07" />
<script type="text/javascript" src="/ask/v1/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="/ask/v1/js/scrollbar.js?v=20151203_07"></script>
<script type="text/javascript" src="/ask/v1/js/slide.js?v=20151203_07"></script>
<script type="text/javascript" src="/ask/v1/js/user_login.js?v=20151203_07"></script>
<!--ends-->
<script type="text/javascript" src="/ask/v1/js/gundong.js?v=20151203_07"></script>
<script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>

</head>
<body>
<!-- 头部开始 -->   
<?php require(APP_ROOT."/headers_new.shtml");?>
<!-- 头部结束 -->
<div class="wd_zj">
    <div class="wd_flz font">
        <ul>
            <li><a href="http://ask.9939.com/" title="首页">首页</a></li>
            <li><a href="http://ask.9939.com/cat.shtml" title=" 科室分类">科室分类</a></li>
            <li class="wd-ts"><a href="http://ask.9939.com/classid/0" title="问题大全">问题大全</a></li>
            <li><a href="http://ask.9939.com/doctorTeam.shtml" title="医生团队">医生团队</a></li>
            <li><a href="http://ask.9939.com/rank.shtml" title="问答排行">问答排行</a></li>
        </ul>
    </div>
</div>

    <div class="mokd">
        <div class="bann">
            <script type="text/javascript">
            var cpro_id="u2315976";
            (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"960",rsi1:"120",pat:"6",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
            </script>
            <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
        </div>
        
            <div class="wd_mian">
            <a href="<?php echo WEB_URL; ?>" title="久久健康网">久久健康网</a>>
            <a href="<?php echo ASK_URL; ?>" title="久久问医">久久问医</a>
                <?php
                $keshiid = $this->classid;
                $ks_cache = $this->ks_cache;
                $htmlStr = '';
                $keshicid = 0;
//                print_r($ks_cache[$keshiid]);
//                exit;
                while (isset($ks_cache[$keshiid])) {
                    
                    $jb_url = "/classid/$keshiid";
                    $ks_name = $ks_cache[$keshiid]['name'];
                    if($keshicid!==0){
                        $htmlStr = '><a href="' .$jb_url. '" title="' . $ks_name. '" class="a_bol">' . $ks_name . '</a>' . $htmlStr;
                    }else{
                        $htmlStr = '><a href="/disease/' . $ks_cache[$this->classid]['id'] . '" class="a_bol" title="' . $ks_name. '">'.$ks_cache[$keshiid]['name'].'</a> ';
                    }
                    $keshiid = $ks_cache[$keshiid]['pID'];
                    $keshicid = $ks_cache[$keshiid]['child'];
                    if ($keshiid == 0)
                        break;
                }
                
                if ($htmlStr != '><a href="" title="" class="a_bol"></a>') {
                    $boolzilei = true; //表示为选择科室
                    echo $htmlStr;
                } 
                echo "> 问题列表";
                ?>
            <!--a href="">内科</a>><a href="" title="" class="a_bol">流行感冒</a-->
          </div>
            <!--
            <div class="disename dyh">
                <h3 class="mr11 fl">慢性腹泻</h3><cite class="mr17 cor666 fl">(别名：拉肚子)</cite><span class="lookwik dst fl"><a href="">查看百科</a></span>
            </div>
            -->
            <div class="container">
             <div class="w678 mr20 fl">
                <!--
                <div class="disnom">
                <form>
                    <div class="ln32 dyh clearfix">
                        <span class="screen">问题筛选：</span>
                          <span class="answe">
                            <label>
                                <input type="checkbox" value="1" >
                                <span>医生回答</span>
                            </label>
                        </span>
                        <span class="answe">
                            <label>
                            <input type="checkbox" value="2"><span>满意答案</span></label></span>
                            <span class="gender">
                                 <i class="cor999">全部性别</i>
                                 <input type="text" value="全部性别">
                             <ol style="display: none;">
                                <li class="">男</li>
                                <li>女</li>
                                <li>全部性别</li>
                            </ol>
                        </span>
                         <span class="gender">
                                 <i class="cor999">全部人群</i>
                                 <input type="text" value="全部人群">
                             <ol style="display: none;">
                                <li class="">婴儿</li> 
                                <li>儿童</li>
                                <li>孕妇</li>
                                <li>老年</li>
                                <li>其他</li>
                                <li>全部人群</li>
                            </ol>
                        </span>
                        </div>
                    <div class="ln32 mT11 dyh clearfix">
                        <span class="screen">并发症状：</span>
                        <span class="answe">
                            <label>
                                <input type="checkbox" value="畏寒"><span>畏寒</span></label></span>
                        
                        <span class="answe">
                            <label>
                                <input type="checkbox" value="头痛"><span>头痛</span></label></span>
                        
                        <span class="answe">
                            <label>
                                <input type="checkbox" value="浑身酸痛"><span>浑身酸痛</span></label></span>
                        
                        <span class="answe">
                            <label>
                                <input type="checkbox" value="咽喉疼痛"><span>咽喉疼痛</span></label></span>
                        
                        <span class="answe">
                            <label>
                              <input type="checkbox" value="发烧"><span>发烧</span></label></span>
                    </div>
                  </form>
                </div>
                -->
                <div class="disban" style="display:none;">
                    <script type="text/javascript">
                    var cpro_id="u2315979";
                    (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"680",rsi1:"120",pat:"6",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
                    </script>
                    <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                </div>
                
            <!--div class="desnum cor666 dst">共<i><?=$this->totalRecord?></i>个关于 <?=$ks_cache[$this->classid]['name']?> 的问题</div-->
                <div class="desnum cor666 dst mhod clearfix"><span>关于</span><span class="citre"><h1 style="font-size:18px;"><?=$this->curword?></h1></span><span>的问题</span></div>
              <!--回答区 开始-->
              <div  class="probsolv">
                  <?php
//                print_r($this->rs);
//                exit;
                  foreach ($this->rs as $v) {
                      foreach ($v['aList'] as $key => $val) {
                          $url = $val['id'] == '' ? '' : 'http://ask.9939.com/id/' . $val['id'];
                          $username = $val['hiddenname'] == 1 ? '匿名' : QLib_Utils_String::cutString($val['nickname'], 5, '...');
                          $sex = $val['sexnn'] == 1 ? '男' : '女';
                          $age = !empty($val['age']) ? $val['age'] : 27;

                          $bestUserId = $val['bestAnswerDetail']['uid'];
                          $bestUserName = $val['bestAnswerDetail']['nickname'];
                          $bestUserPic = $val['bestAnswerDetail']['pic'] == '' ? HOME_9939_URL . '/images/default.jpg' : HOME_9939_URL . $val['bestAnswerDetail']['pic'];
//                        print_r($val['bestAnswerDetail']);
//                        exit;
                          $bestUserContent = strip_tags(trim($val['bestAnswerDetail']['bestAnswer']));
//                        $bestUserContent = preg_replace("/<(.*?)>/", "", $bestUserContent);

                          $title = strip_tags($val['title']);
                          
                          $search_words = explode('|', str_replace(array('(', ')'), '', $v['explain_words']));
                          $replace_words = array();
                          foreach ($search_words as $ke => $va) {
                              $replace_words[] = '<font color="#F60">' . $va . '</font>';
                          }
                          $dis_title = mb_substr($title, 0, 22,'UTF-8');
                          $dis_title = str_replace($search_words, $replace_words, $dis_title);
                          ?>
                <!--question start-->
                <div class="doc_anwer disline">
                    <div class="subtit dyh"><b></b><span class="cor666 dst fr"><i><?=$username?></i>|<i><?=$sex?></i>|<i><?=$age?>岁</i></span><a href="<?=$url?>" target="_blank"><?php echo $dis_title; ?></a></div>
                    <div class="drawall ">
                        <dl class="jodoc  mr27 fl"><dt><a href="http://ask.9939.com/Asking/index?uid=<?=$bestUserId?>"><img src="<?=$bestUserPic?>" alt="" title=""/></a></dt><dd class="mT9"><?=$bestUserName?></dd>
                            <dd class="askhim mT9 dyh"><a href="http://ask.9939.com/Asking/index?uid=<?=$bestUserId?>">向TA提问</a></dd></dl>
                        <div class="doctext fl">
                            <p class="dst"><i></i><?php echo mb_substr($bestUserContent,0,66,'UTF-8');?><a href="<?=$url?>" target="_blank">[详细]</a></p>
                            <div class="mT19">
                                <!--<div class="xgtag mT10 fl"><a class="txtno cor999">相关标签:</a><a href="">腹泻</a><a href="">胃出血</a></div>-->
                                <div class="h23 fr">
                                    <?php
                                    
                                    if($val['bestAnswerDetail']['bestAnswerUID']!==''){
                                    ?>
                                    <span class="descn fl">已采纳</span>
                                    <?php
                                    }
                                    ?>
                                    <span class="mebtime cor999 fl"><?=$val['ctime'];?></span></div>
                            </div>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
                <!--question end-->
                <?php
                    }
                ?>
                
                
                  
            <div class="page clearfix">
                    <?php
                    echo $v['pagehtml'];
                    ?>
                   
            </div>
                <?php
                }
                ?> 
        </div>   
                 
                
              <!--回答区 结束-->
            <!--div class="issues phopr13 ">
                <h4 class="lw5"><a href="" title="健康图谱">健康图谱</a></h4>
                <ul class="mepho mT15 clearfix">
                    <script type="text/javascript">BAIDU_CLB_fillSlot("1123981");</script> 
                </ul>
            </div-->
            <div class="clear"></div>
            
           </div>
              <div class="w300 fl">
                <!--常见用药 结束 -->
                <?php
                if (isset($this->listwords) && !empty($this->listwords)) {
                    ?>
                    
                    <div class = "r_doctor quitr_doctor mTop">
                        <div class = "rquit_line cuols"><h4><span><?php echo  $this->jb_title;?></span>热词</h4></div>
                        <ul class="addrel">
                            <?php foreach ($this->listwords as $key => $value) { ?>
                                <?php
                                $wordsname = QLib_Utils_String::cutString($value['name'], 16, '...');
                                $url = '/top/' . $value['pinyin_initial'] . '/';
                                ?>
                            <li><a href="<?= $url ?> " title="<?= $value['name'] ?>" target="_blank"><h2 style="font-size:14px; font-weight:normal;"><?= $wordsname ?></h2></a></li>
                            <?php } ?> 
                        </ul>
                    </div>
                    <?php
                }else{
                ?>
                <div class="quitr_doctor mTop">
                    <div class="rquit_line"><h2><img src="/ask/v1/images/ltitm1.jpg?v=20151203_07" alt="常见用药" title="常见用药"></h2></div>
                    <div class="drehos">
                        <?php
                            $tuijianDrugs = array(
                                '32'    =>  '1123920',//内科
                                '102'   =>  '1123922',//外科
                                '220'   =>  '1123923',//男科

                                '193'   =>  '1123924',//妇产科
                                '523'   =>  '1123926',//皮肤病
                                '236'   =>  '1123927',//	儿科

                                '276'   =>  '1123929',//	五官科
                                '428'   =>  '1123930',//	中医科
                                '324'   =>  '1123931',//	传染病

                                '371'   =>  '1123933',//	肿瘤科
                                '299'   =>  '1123934',//	整形美容
                                '525'   =>  '1123935',//	心理推荐

                                '15'   =>  '1123936',//	其他推荐
                                '537'   => '1123859'//热门标签等
                            );
                            
                            $drugs = $tuijianDrugs[$this->order];
                            
//                            foreach($tuijianDrugs as $key=>$value){
//                                if( in_array($key, explode(' ',$this->info['class_isid']) ) ){
//                                    echo '<script type="text/javascript">BAIDU_CLB_fillSlot("'.$value.'");</script>';
//                                }
//                            }                
                            ?>
                            <script type="text/javascript">BAIDU_CLB_fillSlot("1123920");</script>
                    </div>
                </div>
                    <?php
                }
                    ?>
                
                
                
                
                
                

                <!--推荐专家 开始 -->
                <div class="r_doctor quitr_doctor mTop">
                    <div class="rquit_line"><h4><img src="/ask/v1/images/ltitm0.jpg?v=20151203_07"  alt="推荐专家" title="推荐专家"></h4></div>
                    <div class="expert pr20">
                        <?php
                        if(isset($this->famousDoctors)) {
                            foreach ($this->famousDoctors as $k => $v) {
                                echo urldecode($v['text']);
                            }
                        }
                        ?>
                    </div>
                </div>
                <!--推荐专家 结束 -->
                    
                    <!--根据热词获取文章 开始-->
                    <div class="r_doctor quitr_doctor mTop">
                        <div class="rquit_line cuols"><h4><span><?=$this->jb_title;?></span>文章</h4></div>
                        <ul class="addrel">
                            <?php foreach ($this->rel_article as $key => $value) {?>
                            <?php $shorttitle = QLib_Utils_String::cutString($value['title'], 16, '...');?>
                            <li><a href="<?=$value['url']?>" title="<?=$value['title']?>" target="_blank"><?=$shorttitle?></a></li>
                            <?php }?>
                        </ul>
                    </div>
                    <!--根据热词获取文章 结束-->
                  <div class="clear"></div>
                  
            <div class="clumn mTop">
                <script type="text/javascript">
                var cpro_id="u2315984";
                (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"17",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0"}
                </script>
                <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
            </div>
            
            <!--推荐医院 开始 -->
                 <div class="quitr_doctor mTop"><div class="rquit_line"><h2><img src="/ask/v1/images/ltitm7.jpg?v=20151203_07" alt="推荐医院" title="推荐医院"></h2></div>
                 <div class="drehos">
                     <?php
                        if(!empty($this->recommendHospital)) {
                            foreach ($this->recommendHospital as $k => $v) {
                                echo urldecode($v['text']);
                            }
                        }
                        ?>
                  </div>
               </div>
            <!--推荐医院  结束-->
 
            <!--div class="quitr_doctor mTop">
                <div class="rquit_line clearfix">
                    <h4 class="rquit_line_h2 fl"><a href="" title="热门文章">热门文章</a></h4>
                    <div class="hottab fl">
                        <a href="http://js.9939.com">健身</a>|<a href="http://food.9939.com">饮食</a>|<a href="http://xinli.9939.com">心理</a>|<a href="http://drug.9939.com">药品</a>|<a href="http://tijian.9939.com">体检</a></div></div>
                <div class="plr10"><ul class="r_hot clearfix">
                        <script type="text/javascript">BAIDU_CLB_fillSlot("1123862");</script> 
                    </ul>
                    <ul class="er_news er_line">
                        <?php
                        foreach ($this->article as $k => $v) {
                            echo '<li><span><a href="'.$v["curl"].'" title="'.$v["channel"].'">['.$v["channel"].']</a></span><span><a href="'.$v["aurl"].'" title="'.$v["title"].'">'.mb_substr($v["title"], 0,12,'UTF-8').'</a></span></li>';
                        }          
                        ?>
                    </ul>
                </div>
            </div-->
            <!--猜你喜欢 开始 -->
            <div class="quitr_doctor noplim">
                <div class="rquit_line  rqure3 clearfix"><h2 class="rquit_line_h2 fl"><img src="/ask/v1/images/ltitm9.jpg?v=20151203_07" alt="猜你喜欢" title="猜你喜欢"></h2></div>
                <div class="clumn mTop">
                    <script type="text/javascript">
                        var cpro_id="u2315986";
                        (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"1",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"0",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",tft:"0",tlt:"1",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
                    </script>
                    <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                </div>
            </div>
            <!--猜你喜欢 结束 -->

                <div class="clear"></div>
            
        </div>
            <div class="clear"></div>
          </div>
<!-- 热搜词 开始-->
                <div class="letter-switch  lett-tab leume  mT25 clearfix">
                    <?php foreach($this->letter_list as $k=>$v) {
                //                        $class_name = ($v['selected']==1? 'class="nols"':'');
                            $class_name =($this->letter==$k)? 'class="currm move"': 'class="currm"';
                        ?>
                        <a  switc="<?php echo $k; ?>"  href="http://ask.9939.com/hot/<?php echo $k; ?>/" target="_blank" <?php echo $class_name; ?> ><?php echo $k; ?></a>
                    <?php } ?>
                </div>
                <div class="lett-tab-con f12 clearfix">
                    <?php $i=0;foreach($this->randWords as $k=>$v){ 
                            $zimu = strtoupper($k);
                            $style =(strtoupper($this->letter)==$zimu)?'':'curro';
                        ?>
                        <div switc-ass="<?php echo $zimu; ?>" class="lett-tab-<?php echo $zimu; ?> hotwords <?php echo $style; ?>"  >
                            <?php
                            if(count($v) > 1){
                                foreach($v as $kk=>$vv){
                                    $url = sprintf('%s%s/',$this->searchurl,  str_replace(' ', '', $vv['pinyin']));
                                    echo '<a href="'.$url.'" title="'.$vv['keywords'].'">'.$vv['keywords'].'</a>';
                                }
                            }
                            ?>
                        </div>
                    <?php $i++;} ?>
                </div>
            <!-- 热搜词 结束-->
            <!-- 底部常见疾病、热门科室 -->
                <!--#include virtual="/include/footer_ask_experience.shtml"--> 
            <!-- 底部常见疾病、热门科室 -->
         <!-- 页面底部 -->
         <!--#include virtual="/ask/ask_footer/ask_footer_new.html"-->
         <!--#include virtual="/public/include/baidu_js_push.php"-->
    <script>
    var _hmt = _hmt || [];
    (function() {
      var hm = document.createElement("script");
      hm.src = "//hm.baidu.com/hm.js?7e9c5ad59825c8cec9d1a0dbe84cfb61";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
    </script>
    <script type="text/javascript">
	$(".gender").hover(function(){$(this).children("ol").stop(true,true).slideToggle(200);	},function() {	$(this).children("ol").stop(true,true).slideUp(200);});
		$(".gender ol li").bind("click",function(){
			var li_text = $(this).text();
			$(this).parent("ol").siblings("i").text(li_text);
			$(this).parent("ol").siblings("input").attr("value",li_text).css('text-align','center');
			$(".gender > ol").hide();
		}).hover(function(){$(this).addClass("li_hover");},function(){$(this).removeClass();});
   if($('.detail_nr').size()){
        $('.detail_nr p a').click(function(){
            $(this).parents('.witshow').toggleClass('accord');
            $(this).siblings('span').toggle();
            $(this).html($(this).html() == '展开' ? '收起' : '展开');
        });
    };
    </script>
</body>
</html>
<?php
//    $cache_data = ob_get_contents();
//    QLib_Cache_Client::setPageCache('pages', $cache_key, $cache_data, 24);
//    ob_flush();
//}
?>