<script>

</script>

<div class="d-grid l-fix" style="overflow:hidden; zoom:1;">
    <div class="col-m">
        <div class="d-box2">
          <div class="d-login-pw">
                  <h3>找回密码</h3>
                    
                        <p class="top name l-fix">1.填写绑定邮箱&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2.接受密码找回邮件&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&gt;&gt;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<strong>3.重置密码</strong></p>
                        <p class=" info name l-fix" id="error"></p>
                        <p class="userInfo name l-fix">
                            <label class="wInfo">重置密码：</label>
                            <input id="pwd" name="info[username]" class="userPassword" type="password">
                        </p>
                        <p class="userInfo ps l-fix">
                            <label class="wInfo">确认密码：</label>
                            <input id="pwd2" name="info[password]" class="userPassword" onkeydown="huiche(event);" type="password">
                        </p>
                         <input id="backurl" name="info[backurl]" value="" type="hidden">
                 
            <p class="dlan" id="button"><a href="javascript:;" onclick="tijiao();"><img class="imgInfo" src="/ask/images/but-tj.gif"></a></p>
                </div>
                </div>
    </div>
    </div>