<?php
//$cache_key = sprintf('%s|%s|%s_%s', 'ask', 'list_'.$this->status, $this->classid, $this->page_now==''?'0':$this->page_now);
//$data = QLib_Cache_Client::getPageCache('pages', $cache_key,24);
//if ($data) {
//    echo $data;
//} else {
//    ob_start();
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo $this->title; ?></title>
        <meta name="Keywords" content="<?php echo $this->keywords; ?>" />
        <meta name="description" content="<?php echo $this->description; ?>" />
        <!--头部-->
        <link rel="stylesheet" type="text/css" href="/ask/v1/css/main.css?v=20160905" />
        <link rel="stylesheet" type="text/css" href="/ask/v1/css/bd_search.css?v=20151203_07" />
        <link rel="stylesheet" type="text/css" href="/ask/v1/css/second.css?v=20160811" />
        <link rel="stylesheet" type="text/css" href="/ask/v1/css/rclumn.css?v=20160805" />

        <script type="text/javascript" src="/ask/v1/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="/ask/v1/js/jquery.placeholder.min.js?v=20151203_07"></script>
        <script type="text/javascript" src="/ask/v1/js/page.js?v=20151203_07"></script>
        <script type="text/javascript" src="/ask/v1/js/scrollbar.js?v=20151203_07"></script>
        <script type="text/javascript" src="/ask/v1/js/slide.js?v=20160811"></script>
        <script type="text/javascript" src="/ask/v1/js/user_login.js?v=20151203_07"></script>
        <script type="text/javascript" src="/ask/v1/js/gundong.js?v=20151203_07"></script>
        <script type="text/javascript" src="/ask/v1/js/DD_belatedPNG.js?v=20151203_07"></script>
        <script type="text/javascript" src="http://cbjs.baidu.com/js/m.js"></script>
        <base  target="_blank"/>
    </head>
    <body>
        <!-- 头部开始 -->   
        <!--#include virtual="/headers_new.shtml"-->  
        <!-- 头部结束 -->
        <div class="wd_zj">
            <div class="wd_flz font">
                <ul>
                    <li><a href="http://ask.9939.com/" title="首页">首页</a></li>
                    <li><a href="http://ask.9939.com/cat.shtml" title=" 科室分类">科室分类</a></li>
                    <li class="wd-ts"><a href="http://ask.9939.com/classid/0" title="问题大全">问题大全</a></li>
                    <li><a href="http://ask.9939.com/doctorTeam.shtml" title="医生团队">医生团队</a></li>
                    <li><a href="http://ask.9939.com/rank.shtml" title="问答排行">问答排行</a></li>
                    <li><a href="http://ask.9939.com/jingyan/" title="健康经验">健康经验</a></li>
                </ul>
            </div>
        </div>
        <div class="mokd">
            <!-- 百度广告位1 -->
            <div class="bann">
                <script type="text/javascript">
                    var cpro_id="u2315937";
                    (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"960",rsi1:"120",pat:"6",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
                </script>
                <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
            </div>
            <div class="wd_mian font">
                <?php
                $keshiid = $this->classid;
                $ks_cache = $this->ks_cache;
                $ks_nav = $this->ks_nav;
                $htmlArr = array();
                $htmlArr[] = '<a href="' . WEB_URL . '" title="久久健康网">久久健康网</a>';
                $htmlArr[] = '<a href="' . ASK_URL . '" title="久久问医">久久问医</a>';
                $htmlStr = '';
                foreach ($ks_nav as $k => $v) {
                    $jb_url = $v['url'];
                    $ks_name = $v['name'];
                    $htmlStr = '<a href="' . $jb_url . '" title="' . $ks_name . '" class="a_bol">' . $ks_name . '</a>';
                    $htmlArr[] = $htmlStr;
                }

                $htmlArr[] = '问题列表';
                echo implode('>', $htmlArr);

                $ret_arr = array_slice($ks_nav, 0, 1);
                $level1_id = count($ret_arr) > 0 ? $ret_arr[0]['id'] : 0;
                $ret_arr = array_slice($ks_nav, 1, 1);
                $level2_id = count($ret_arr) > 0 ? $ret_arr[0]['id'] : 0;

                $ret_arr = array_slice($ks_nav, 2, 1);
                $level3_id = count($ret_arr) > 0 ? $ret_arr[0]['id'] : 0;
                ?>
            </div>
            <?php $target = ' target="_blank"'; ?>
            <div class="container w1000 font">
                <!--左侧开始-->
                <div class="w678  mr20 fl">
                    <!--科室分类-->  
                    <div class="administr">
                        <div class="hr_rig01">
                            <ul class="ksul clearfix">
                                <?php
                                $n = 0;
                                $len_dzjb = count($this->dzjb);
                                foreach ($this->dzjb as $k => $v) {
                                    if ($v['child']) {
                                        $curr_class_id = $v['id'];
                                        $class = ($curr_class_id == $level1_id) ? "on" : "";
                                        $style = ($k == $len_dzjb - 1) ? 'style=" padding:0 12px;"' : "";
                                        echo '<li class="' . $class . '" data-nav-id="'.$curr_class_id.'"><a target="_self"  href="' . $v['url'] . '" title="' . $v['name'] . '" ' . $style .$target. '>' . $v['name'] . '</a></li>';
                                        $n++;
                                    }
                                }
                                ?>

                            </ul>
                        </div>              
                        <div class="hr_left01">
                            <?php
                            $n = 1;
                            foreach ($this->dzjb as $k => $v) {
                                if ($v['child']) {
                                    $curr_class_id = $v['id'];
                                    $display = ($curr_class_id == $level1_id) ? "block" : "none";
                                    echo '<dl class="mebox" id="mebox_'.$curr_class_id.'"  name="mebox_'.$curr_class_id.'"   data-nav-id="'.$curr_class_id.'"  style=" display:' . $display . ';"><div class="mebox_a">';
                                    //二级科室
                                    $m = 0;
                                    foreach ($v['child'] as $key => $val) {

                                        $active = ($val['id'] == $level2_id) ? "active" : "";
                                        echo '<a target="_self" href="' . $val['url'] . '" class="' . $active . '" data-id="tab_pole' . $n . '" title="' . $val['name'] . '"' . $target . '>' . $val['name'] . '</a>';
                                        $m++;
                                    }
                                    echo '</div>';

                                    echo '<div class="depart_third" id="div_tab_pole' . $n . '">';
                                    //三级科室
                                    $m = 0;
                                    foreach ($v['child'] as $key => $val) {

                                        $display = ($val['id'] == $level2_id) ? "block" : "none";
                                        $m++;
                                        echo '<div class="meline clearfix" data-pid="'.$val['id'].'" style=" display:' . $display . ';">';
                                        echo '<div class="cinfo fl">';
                                        
                                        $aTemp = array();
                                        foreach ($this->ks_cache as $key1 => $val1) {
                                            if ($val1['pID'] == $val['id']) {
                                                $j = $val1['listorder'];
                                                $aTemp[$j] = $val1;
                                            }
                                        }
                                        ksort($aTemp);
                                        foreach ($aTemp as $val2) {
                                            $disease_url = '/disease/' . $val2['id'];
                                            if($val2['class_level3'] == 0){
                                                $disease_url = '/classid/' . $val2['id'];
                                            }
                                            $style_class = ($val2['id'] == $level3_id) ? "active" : "";
                                            echo '<a target="_blank" href="'.$disease_url.'" class="' . $style_class . '" title="' . $val2["name"] . '"' . $target . '>' . $val2['name'] . '</a>';
                                        }
                                        echo '</div><a class="folen fr">展开&nbsp;∨</a>';
                                        echo '</div>';
                                    }

                                    echo '</div>';

                                    echo '</dl>';
                                    $n++;
                                }
                            }
                            ?>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="l_ques" style="margin-top:17px;">
                        <div class="lw_tab nosanme clearfix">
                            <a href="/classid/<?php echo sprintf('%d-%s-%d', $this->classid, 'all', 1); ?>" target="_self" name="tab_status_3" id="tab_status_3" class="<?php echo $this->status == 3 ? "indexahover" : ""; ?>" style=" border-left:none;">全部问题</a>
                            <a href="/classid/<?php echo sprintf('%d-%s-%d', $this->classid, 1, 1); ?>" target="_self" name="tab_status_1" id="tab_status_1" class="<?php echo $this->status == 1 ? "indexahover" : ""; ?>">已解决问题</a>
                            <a href="/classid/<?php echo sprintf('%d-%s-%d', $this->classid, 4, 1); ?>" target="_self" name="tab_status_4" id="tab_status_4" class="<?php echo $this->status == 4? "indexahover" : ""; ?>">待解决问题</a>
                            <a href="/classid/<?php echo sprintf('%d-%s-%d', $this->classid, 2, 1); ?>" target="_self" name="tab_status_2" id="tab_status_2" class="<?php echo $this->status == 2 ? "indexahover" : ""; ?>">悬赏问题</a>
                        </div>
                        <div class="kebox" name="n2Tab22Content" id="n2Tab22Content">
                            <div class="kmname clearfix">
                                <div class="lKtit fl los">
                                    <span>提问标题</span>
                                </div>
                                <div class="rKtit fl ros">
                                    <span class="hf_num">回复数</span>
                                    <span class="zx_num">状态</span>
                                    <span class="tw_num">提问时间</span>
                                </div>
                            </div>
                            <div class="Bigbox">
                                <?php
                                $row_index = 0;
                                $encoding = 'utf8';
                                foreach ($this->ask_list as $k => $v) {
                                    $point = $v['point'];
                                    $cntime = $v['cntime'];

                                    $adopt = ($v['bestanswer'] == 0) ? '' : '<span class="kscn">已采纳</span>';
//                                    $solve_class = ($v['status'] == 0) ? 'class="wprob"' : 'class="yprob"';
                                    $solve_class = ($v['answernum'] == 0) ? 'class="wprob"' : 'class="yprob"';
//                                    $solve = ($v['status'] == 1) ? '已解决' : '待解决';
                                    $solve = ($v['answernum'] > 0) ? '已解决' : '待解决';
                                    $reward = ($point > 0) ? '<span class="xuslogo" title="悬赏问题"></span>' : '';
                                    $div_row_class = ($row_index % 2 == 0) ? 'class="state yobg clearfix"' : 'class="state nobg clearfix"';
                                    
                                    
                                    $classid = $v['jb_classid'];
                                    $is_disease = isset($this->ks_cache[$classid]['is_disease'])?$this->ks_cache[$classid]['is_disease']:1;
                                    $jb_name = $v['jb_name'];
                                    $id = $this->ks_cache[$classid]['id'];
                                    $jb_url =$is_disease ==1? "/disease/$id":"/classid/$id";
                                    $ask_url = "/id/" . $v['id'];
                                    $title = strip_tags($v['title']);
                                    $short_title = mb_substr($title, 0, 18, $encoding);
                                    $row_index++;
                                    ?>

                                    <div <?php echo $div_row_class; ?>>
                                        <div class="lpom tuo fl">
                                            <span>[<a href="<?php echo $jb_url; ?>"><?php echo $jb_name; ?></a>]</span>     
                                            <span><a href="<?php echo $ask_url; ?>" title="<?php echo $title; ?>"><?php echo $short_title; ?></a></span>
                                            <?php
                                            echo $adopt;
                                            echo $reward;
                                            ?>   
                                        </div>
                                        <div class="rpom fr">
                                            <span class="ms_num"><?php echo $v['answernum'] ?></span>
                                            <span <?php echo $solve_class; ?>><?php echo $solve; ?></span>
                                            <span class="asktime"><?php echo $cntime; ?></span>
                                        </div>
                                    </div>

                                <?php } ?>
                            </div>
                            <div class="page clearfix">
                                <?php
                                if ($this->total_pages > 1) {
                                    $total_page = $this->total_pages;
                                    $current_page = $this->page_now;
                                    //显示分页的数量
                                    $dis_page_count = 6;

                                    if ($current_page > $total_page) {
                                        $current = $total_page;
                                    }
                                    if ($current_page < 1) {
                                        $current = 1;
                                    }

                                    $sUrl = $this->page_base_url;

                                    $sOutput = '';
                                    if ($current_page > 1) {
//                                            $sOutput.='<span class="left">';
//                                            $sOutput.='<a href="' . $sUrl . '-1" target="_self" >首页</a>';    //输出页数
                                        $sOutput.='<a href="' . $sUrl . '-' . ($current_page - 1) . '"  title="上一页" target="_self" class="lpage_a" ><<上一页</a>';    //输出页数
//                                            $sOutput.='</span>';
                                    }
                                    // if($current_page>=$dis_page_count){
                                    //     $sOutput.='<a>...</a>';    //输出页数
                                    // }
                                    $start = min(floor(max(($current_page - floor($dis_page_count / 2)), 1)), max(($total_page - $dis_page_count + 1), 1));

                                    $end = min(($start + $dis_page_count - 1), $total_page);

//                                        $sOutput.='<span class="num">';
                                    for ($i = $start; $i <= $end; $i++) {
                                        if ($current_page == $i) {
                                            $sOutput.='<a href="' . $sUrl . '-' . $i . '" class="now" target="_self" >' . $i . '</a>';    //输出页数
                                        } else {
                                            $sOutput.='<a href="' . $sUrl . '-' . $i . '" target="_self" >' . $i . '</a>';    //输出页数
                                        }
                                    }
//                                        $sOutput.='</span>';
                                    if ($current_page < $total_page) {
//                                            $sOutput.='<span class="right">';
                                        $sOutput.='<a href="' . $sUrl . '-' . ($current_page + 1) . '"  target="_self"  title="下一页" class="lpage_a">下一页>></a>';
//                                            $sOutput.='<a href="' . $sUrl .'-'. ($total_page) . '"  target="_self"  title="尾页">尾页</a>';
//                                            $sOutput.='</span>';
                                    }
                                    $sOutput .='<a href="/wenti/1.html"  target="_blank"  title="更多" class="lpage_a">更多>></a>';
                                    echo $sOutput;
                                }
                                ?>
                            </div>
                            <div class="clear"></div>         
                        </div>
                    </div> 
                    <!--全部问题  结束--> 
                    <!--大家都在看 开始 -->  
                    <div class="rq_wd mTop20">
                        <div class="q_pic"><img src="http://ask.9939.com/ask/v1/images/11.jpg?v=20151203_07"/></div>
                        <div class="qlab">
                            <?php
                            $top_dis = array(
                                '32' => 1140002,//内科
                                '102' => 1140013,//外科
                                '220' => 1140015,//男科
                                '193' => 1140016,//妇产科
                                '523' => 1140017,//皮肤性病科
                                '236' => 1140028,//儿科
                                '276' => 1140029,//五官科
                                '428' => 1140030,//中医科
                                '324' => 1140031,//传染病科
                                '371' => 1140032,//肿瘤科
                                '299' => 1140033,//整形美容
                                '525' => 1140045,//心理
                                '15' => 1140046,//其他
                                '537'=>1140002//热门标签等等
                            );
                            $top = $top_dis[$this->order];
                            ?>
                            <script type="text/javascript">BAIDU_CLB_fillSlot("<?php echo $top; ?>");</script>
                        </div>
                    </div>
                    <!--热门标签 结束-->
                    <!-- SEO百度广告位3-->
                    <div class="wdad mTop20">
                        <script type="text/javascript">
                        var cpro_id="u2315945";
                        (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"680",rsi1:"130",pat:"6",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
                        </script>
                        <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                    </div>
                    <!-- 在线提问 -->
                    <div class="wmdoc_ask mTop20" style="display:none;">
                        <form  action="/askt/do/do/save"  method="post"  id="save_question" name="save_question"  target="_self" >
                            <div class="ksAks mTop">
                                <div class="kotit"><span><img  src="/ask/v1/images/ltitm3.jpg?v=20151203_07"/></span><span class="qjd">（万名医生给您做疾病解答）</span></div>
                                <div class="xz_inpue clearfix">
                                    <div class="mRit36 mH10 fl">
                                        <b class="fl">性  别：</b>                          
                                        <div class="mcko fl">
                                            <span class="fl">
                                                <input type="radio" class="w14 fl css_rd_sex" id="rd_male" name="info[sexnn]" checked data-flag="wd_ask" data-field="sexnn"  value="1"  />
                                                <label class="nan fl">男</label>
                                            </span>
                                            <span class="clob5 fl">|</span>
                                            <span class="fl">
                                                <input type="radio" class="w14 fl css_rd_sex" id="rd_female"  name="info[sexnn]" data-flag="wd_ask" data-field="sexnn" value="2" />
                                                <label class="women fl" >女</label>
                                            </span>
                                        </div>
                                    </div>
                                    <div class="mRit36 fl">
                                        <b class="mH10 fl">年  龄：</b>
                                        <div class="ques_lined5 fl">
                                            <input id="info[age]" name="info[age]" type="text" class="quesage"  data-flag="wd_ask" data-field="age"  value="" placeholder="如：28" />
                                            <input type="hidden" id="info[age_unit]" name="info[age_unit]"  data-flag="wd_ask" data-field="age_unit"  value="0" />
                                            <div class="showage fr mp">
                                                <span class="ksui">岁</span>
                                                <div class="ageLx rol" style="display:none;">
                                                    <a data-id="0">岁</a>
                                                    <a data-id="1">月</a>
                                                    <a data-id="2">天</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="mRit36 fl">
                                        <b class="mH10 fl">选择科室：</b>
                                        <div class="ques_lined5 quesw162 ques_xla fl">
                                            <input id="txt_class_name" name="txt_class_name" type="text"  class="quit_writ" readonly="true"   placeholder="请您选择科室！" value="" />
                                            <div class="showage ks_show fr" style="z-index:1000;"></div>

                                            <!--科室弹框 开始-->
                                            <div class="ksxl dopc1" id="div_select_keshi">
                                                <div class="choks pl18">
                                                    <p class="ple_ks">请选择科室</p>
                                                    <p  class="cho_zj">（选择科室专家能更快为您解答）</p>
                                                    <div class="xlerr">
                                                        <a><img  src="http://ask.9939.com/ask/v1/images/xlerr.png"/></a>
                                                    </div>
                                                </div>
                                                <div class="ks_xlab pl18 mTop8" id="div_ks_tips"><b class="cko_wrblue">您选择的科室：</b></div>
                                                <div class="choks_mian clearfix">
                                                    <!--一级科室 开始-->
                                                    <div class="choksone  chosame choks_line mTop12"><h2>一级科室</h2>
                                                        <div class="kstw_a kstw_one mTop12" id="ks_level1">
                                                            <?php
                                                            foreach ($this->dzjb as $k => $v) {
                                                                $class_id = $v['id'];
                                                                $class_name =$v["name"]; 
                                                                echo '<a class="" id="ks_' . $k . '" data-id="'.$class_id.'" data-name="' . $class_name . '" >' . $class_name . '</a>';
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                    <!--一级科室 结束--> 
                                                    <!--二级科室 开始-->
                                                    <div class="bigTwo"  id="ks_level2">
                                                        <?php
                                                        foreach ($this->dzjb as $k => $v) {
                                                            echo '<div class="chokstwo chosame choks_line mTop12 div_kz_ks_level2" style="display:none;"><h2>二级科室</h2><div class="kstw_a  mTop12 kstw_two">';
                                                            foreach ($v['child'] as $ke => $va) {
                                                                $class_id = $va['id'];
                                                                $class_name =$va["name"]; 
                                                                echo '<a class="" id="ks_' .$class_id . '" data-id="'.$class_id.'" data-name="' . $class_name . '">' . $class_name . '</a>';
                                                            }
                                                            echo '</div></div>';
                                                        }
                                                        ?>
                                                    </div>
                                                    <!--二级科室 结束--> 
                                                    <!--三级科室 开始-->
                                                    <div class="bigTre"  id="ks_level3"></div> 
                                                    <!--三级科室 结束-->                            
                                                </div>
                                                <div class="chock pl18 mTop12">
                                                    <span><input type="checkbox"  class="cho_bqc" ></span>
                                                    <span id="span_ks_unclear" class="colyel">我不清楚是哪个科室</span>  
                                                </div>
                                                <p class="cho_confirm">确 定</p>
                                            </div>
                                            <!--科室弹框结束-->
                                        </div>
                                    </div>
                                </div>  

                                <div class="ktex mTop15">
                                    <h2>请概括描述您的病情及疑问</h2>
                                    <div class="txa ms_tit">
                                        <textarea id="info[title]" name="info[title]" class="asktex_d css_txt"   data-flag="wd_ask" data-field="title" max_char_num="30" maxlength="30"  placeholder="请简述您的问题作为标题"></textarea>
                                        <p class="fr asknum">0/30</p>
                                    </div>
                                </div>
                                <div class="ktex mTop15">
                                    <h2>请详细描述您的病情症状</h2>
                                    <div class="txa twnose">
                                        <textarea id="info[content]" name="info[content]"  class="asktex_b css_txt"  data-flag="wd_ask" data-field="content"  max_char_num="500"  maxlength="500"  placeholder="描述越清楚，医生回答越详细"></textarea>
                                        <p class="fr asknum">0/500</p>
                                    </div>
                                </div>
                                <div class="yzcl mTop15">
                                    <div class="fl">
                                        <b class="mH10 fl">验 证 码：</b>
                                        <div class="ques_lined5 ques_w55 fl">
                                            <input type="text" id="verifyt" name="verifyt"  class="quesage"/>
                                        </div>
                                        <div class="pic_yzm fl">
                                            <img id="verifyyzmt" name="verifyyzmt" src="/askt/verify?<?php echo rand(); ?>" onclick="javascript:jp_helper.refresh_code();" style="cursor: pointer;" />
                                        </div>
                                    </div>
                                </div>
                                <div class="qask qaskce mwTop14">
                                    <input  type="button" id="btn_submit_question" name="btn_submit_question" value="">
                                </div>
                            </div>
                            <input type="hidden" name="info[unclear]" id="info[unclear]" data="wd_ask" data-field="unclear" value="0" />
                            <input type="hidden" name="info[class_level1]" id="info[class_level1]" data="wd_ask" data-field="class_level1" value="0" />
                            <input type="hidden" name="info[class_level2]" id="info[class_level2]" data="wd_ask" data-field="class_level2" value="0" />
                            <input type="hidden" name="info[class_level3]" id="info[class_level3]" data="wd_ask" data-field="class_level3" value="0" />
                            <input type="hidden" name="info[classid]" id="info[classid]" data="wd_ask" data-field="classid" value="0" />
                        </form>
                    </div>
                    <!-- 在线提问结束 -->
                </div>
                <!--左侧结束-->    

                <!--右侧开始-->
                <div class="w300 fl">
                    <div class="clumn mTop">
                    <script type="text/javascript">
                    var cpro_id="u2315960";
                    (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"17",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0"}
                    </script>
                    <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                    </div>
                    
                    <!--推荐专家 开始 -->
                    <div class="r_doctor quitr_doctor mTop">
                        <div class="rquit_line"><h4><img src="/ask/v1/images/ltitm0.jpg?v=20151203_07"  alt="推荐专家" title="推荐专家"></h4></div>
                        <div class="expert pr20">
                            <?php
                            if(isset($this->famousDoctors)) {
                                foreach ($this->famousDoctors as $k => $v) {
                                    echo urldecode($v['text']);
                                }
                            }
                            ?>
                        </div>
                    </div> 
                    <!--推荐专家 结束-->
                    <!--常见用药 开始 -->
                    <?php
                    if (isset($this->listwords) && !empty($this->listwords)) {
                        ?>

                        <div class = "r_doctor quitr_doctor mTop">
                            <div class = "rquit_line cuols"><h4><span><?php echo $this->jb_title; ?></span>热词</h4></div>
                            <ul class="addrel">
                                <?php foreach ($this->listwords as $key => $value) { ?>
                                    <?php
                                    $wordsname = QLib_Utils_String::cutString($value['name'], 16, '...');
                                    $url = '/top/' . $value['pinyin_initial'] . '/';
                                    ?>
                                    <li><a href="<?= $url ?> " title="<?= $value['name'] ?>" target="_blank"><h2 style="font-size:14px; font-weight:normal;"><?= $wordsname ?></h2></a></li>
                                <?php } ?> 
                            </ul>
                        </div>
                        <?php
                    } else {
                        ?>
                        <div class="r_doctor quitr_doctor mTop">
                            <div class="rquit_line"><h4><img src="/ask/v1/images/ltitm1.jpg?v=20151203_07" alt="常见用药" title="常见用药"></h4></div>
                            <div class="drehos">
                                <?php
                                $drugs_array = array(
                                    '32' => 1123920, //内科
                                    '102' => 1123920, //外科
                                    '220' => 1123920, //男科
                                    '193' => 1123920, //妇产科
                                    '523' => 1123920, //皮肤性病科
                                    '236' => 1123920, //儿科
                                    '276' => 1123920, //五官科
                                    '428' => 1123920, //中医科
                                    '324' => 1123920, //传染病科
                                    '371' => 1123920, //肿瘤科
                                    '299' => 1123920, //整形美容
                                    '525' => 1123920, //心理
                                    '15' => 1123920, //其他
                                    '537' => 1123859//热门标签等等
                                );
                                $drugs = 1123859;
                                if (isset($drugs_array[$this->order])) {
                                    $drugs = $drugs_array[$this->order];
                                }
                                ?>
                                <script type="text/javascript">BAIDU_CLB_fillSlot("<?php echo $drugs; ?>");</script>
                            </div>
                        </div>
                        <?php
                    }
                    ?>
                    <!--常见用药 结束 -->
                    
                    <!--根据热词获取文章 开始 -->
                    <div class="r_doctor quitr_doctor mTop">
                        <div class="rquit_line cuols"><h4><span><?=$this->jb_title;?></span>文章</h4></div>
                        <ul class="addrel">
                            <?php foreach ($this->rel_article as $key => $value) {?>
                            <?php $shorttitle = QLib_Utils_String::cutString($value['title'], 16, '...');?>
                            <li><a href="<?=$value['url']?>" title="<?=$value['title']?>" target="_blank"><?=$shorttitle?></a></li>
                            <?php }?>
                        </ul>
                    </div> 
                    <!--根据热词获取文章  结束-->   
                    <!--推荐医院 开始 -->
                    <div class="r_doctor quitr_doctor mTop"><div class="rquit_line"><h4><img src="/ask/v1/images/ltitm7.jpg?v=20151203_07" alt="推荐医院" title="推荐医院"></h4></div>
                        <div class="drehos claerdfix">
                            <?php
                            if(!empty($this->recommendHospital)) {
                                foreach ($this->recommendHospital as $k => $v) {
                                    echo urldecode($v['text']);
                                }
                            }
                            ?>
                        </div>
                    </div> 
                    <!--推荐医院  结束-->
                    <div class="quitr_doctor noplim">
                        <div class="rquit_line  rqure3 clearfix"><h4 class="rquit_line_h4 fl"><img src="/ask/v1/images/ltitm9.jpg?v=20151203_07" alt="猜你喜欢" title="猜你喜欢"></h4></div>
                        <div class="clumn mTop">
                            <script type="text/javascript">
                            var cpro_id="u2315961";
                            (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"1",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"0",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0",tft:"0",tlt:"1",ptbg:"90",piw:"0",pih:"0",ptp:"0"}
                            </script>
                            <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                        </div>
                    </div>
                    <div class="clumn">
                        <script type="text/javascript">
                        var cpro_id="u2315964";
                        (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"17",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#000000",titSU:"0"}
                        </script>
                        <script src="http://cpro.baidustatic.com/cpro/ui/c.js" type="text/javascript"></script>
                    </div>
                </div>
                <div  class="clear"></div>
            </div>
            <!-- 热搜词 开始-->
                <div class="letter-switch  lett-tab leume  mT25 clearfix">
                    <?php foreach($this->letter_list as $k=>$v) {
                //                        $class_name = ($v['selected']==1? 'class="nols"':'');
                            $class_name =($this->letter==$k)? 'class="currm move"': 'class="currm"';
                        ?>
                        <a  switc="<?php echo $k; ?>"  href="http://ask.9939.com/hot/<?php echo $k; ?>/" target="_blank" <?php echo $class_name; ?> ><?php echo $k; ?></a>
                    <?php } ?>
                </div>
                <div class="lett-tab-con f12 clearfix">
                    <?php $i=0;foreach($this->randWords as $k=>$v){ 
                            $zimu = strtoupper($k);
                            $style =(strtoupper($this->letter)==$zimu)?'':'curro';
                        ?>
                        <div switc-ass="<?php echo $zimu; ?>" class="lett-tab-<?php echo $zimu; ?> hotwords <?php echo $style; ?>"  >
                            <?php
                            if(count($v) > 1){
                                foreach($v as $kk=>$vv){
                                    $url = sprintf('%s%s/',$this->searchurl,  str_replace(' ', '', $vv['pinyin']));
                                    echo '<a href="'.$url.'" title="'.$vv['keywords'].'">'.$vv['keywords'].'</a>';
                                }
                            }
                            ?>
                        </div>
                    <?php $i++;} ?>
                </div>
            <script>
                $('.currm').mousemove(function () {
                    var zimu = $(this).attr('switc');
                    var className=".lett-tab-" + zimu;
                    $('.move').removeClass('move');
                    $(this).addClass('move');
                    var div=$(".lett-tab-con").find(className);
                    $(".lett-tab-con div").addClass('curro');
                    if(div){
                        div.removeClass('curro');
                    }
                }).click(function(){
//                    return false;
                });
            </script>
            <!-- 热搜词 结束-->
            <!-- 底部常见疾病、热门科室 -->
                <!--#include virtual="/include/footer_ask_experience.shtml"--> 
            <!-- 底部常见疾病、热门科室 -->
            <!-- 页面底部 -->
            <!--#include virtual="/ask/ask_footer/ask_footer_new.html"--> 
            <!--#include virtual="/ask/speediness_questions.html"-->
            <script>
            var _hmt = _hmt || [];
            (function() {
              var hm = document.createElement("script");
              hm.src = "//hm.baidu.com/hm.js?d0e72bff43bc47b182b83c5dad5596aa";
              var s = document.getElementsByTagName("script")[0]; 
              s.parentNode.insertBefore(hm, s);
            })();
            </script>
            <script type="text/javascript">
                
                var jp_qas = {
                    save:function(){
                        var title = $("[data-field='title']").val();
                        var content = $("[data-field='content']" ).val();
                        var age = $("[data-field='age']" ).val();
                        
                        if( this.empty( age ) ) {
                            alert( "请输入年龄!" );
                            $("[data-field='age']").focus();
                            return false;
                        }
                        
                        var reg_num =/(^[0]|[^\d])/i;
                        if(reg_num.test(age)){
                            alert('年龄格式不正确!如：28');
                            $("[data-field='age']").focus();
                            return false;
                        }
                        if( this.empty( title ) ) {
                            alert( "请输入问题标题!" );
                            $("[data-field='title']").focus();
                            return false;
                        }
                        
                        var str_title = String(title).replace(/[\n\r]/ig,'回车');
                        var arr_str_title = str_title.match(/./ig);
                        var title_iLen = arr_str_title.length;
                        if(parseInt(title_iLen)<5){
                            alert( "病情描述字数应该大于5字，小于30字" );
                            $("[data-field='title']").focus();
                            return false;
                        }
                        
                        if( this.empty( content ) ) {
                            alert( "请输入病情描述!" );
                            $("[data-field='content']").focus();
                            return false;
                        }
                        var str_v = String(content).replace(/[\n\r]/ig,'回车');
                        var arr_str = str_v.match(/./ig);
                        var iLen = arr_str.length;
                        if(parseInt(iLen)<20){
                            alert( "病情描述字数应该大于20字，小于500字" );
                            $("[data-field='content']").focus();
                            return false;
                        }
                        $("#save_question").submit();
                    },
                    empty: function( obj ) {
                        if( typeof obj !== "undefined" && obj !== null && obj !== "" ) {
                            return false;
                        }
                        return true;
                    }
                }
                
                var jp_helper = {
                    get_verify_flag:true,
                    chgRemark:function(obj){
                        var max_char_num = parseInt($(obj).attr("max_char_num")) ;
                        var ts_p = $(obj).next();
                        var v = $(obj).val();
                        var str_v = String(v).replace(/[\n\r]/ig,'回车');
                        var arr_str = str_v.match(/./ig);
                        var iLen =arr_str==null?0: arr_str.length;
                        if(parseInt(iLen)>max_char_num){
                            var rs = str_v.substr(0,max_char_num).replace(/(回车)/ig,'\n');
                            $(obj).val(rs);
                            iLen = max_char_num;
                        }  
                        $(ts_p).html(iLen+'/'+max_char_num);
                        return false;
                    },
                    refresh_code:function(){
                        if(!this.get_verify_flag){
                            return;
                        }
                        this.get_verify_flag = false;
                        var str="/askt/verify?"+(new Date()).getTime();
                        $("#verifyyzmt").attr("src",str);
                        $("#verifyyzmt").show();
                        this.get_verify_flag = true;
                    }
                }
                
                var jp_keshi ={
                    show_level_fst:function(){
                        jp_keshi.clear();
                        $("#div_select_keshi").show();
                    },
                    show_level_sec:function(){
                        
                    },
                    show_level_trd:function(){
                        
                    },
                    set_ks_tips:function(){
                        var tips_arr=[];
                        var dis_ks_name = [];
                        $("#div_select_keshi").find('.active').each(function(){
                            var ks_name = $(this).attr("data-name");
                            dis_ks_name.push(ks_name);
                            var nav = '<a class="ks_xz2"  href="javascript:">' +ks_name + '</a>'
                            tips_arr.push(nav);    
                        });
                        var html ='<b class="cko_wrblue">您选择的科室：</b>'+tips_arr.join('>');
                        $("#div_ks_tips").html(html);
                        this.set_ks_disname(dis_ks_name[dis_ks_name.length-1]);
                        this.set_ks_ids();
                        this.set_ks_unclear();
                    },
                    set_ks_disname:function(name){
                        $("#txt_class_name").val(name);
                    },
                    set_ks_unclear:function(){
                        var cbx_flag = $('.cho_bqc').prop('checked');
                        if (cbx_flag) {
                            $("[data-field='unclear']").val("1");
                        } else {
                            $("[data-field='unclear']").val("0");
                        }
                    },
                    set_ks_ids:function(){
                        var sel_class_level1 = $("#ks_level1").find(".active");
                        var sel_class_level2 = $("#ks_level2").find(".active");
                        var sel_class_level3 = $("#ks_level3").find(".active");
                        
                        var class_level1 = sel_class_level1.length>0?sel_class_level1.attr('data-id'):0;
                        var class_level2 = sel_class_level2.length>0?sel_class_level2.attr('data-id'):0;
                        var class_level3 = sel_class_level3.length>0?sel_class_level3.attr('data-id'):0;
                        $("[data-field='class_level1']").val(class_level1);
                        $("[data-field='class_level2']").val(class_level2);
                        $("[data-field='class_level3']").val(class_level3);
                        $("[data-field='classid']").val(class_level3);
                        if(class_level3>0){
                            $('.cho_bqc').prop("checked","");
                            $('.cho_bqc').prop("disabled",true);
                            $('#span_ks_unclear').attr("class","change-color");
                        }else{
                            $('.cho_bqc').prop('disabled',false);
                            $('#span_ks_unclear').attr("class","colyel");
                        }
                    },
                    hide:function(){
                        jp_keshi.clear();
                        $("#div_select_keshi").hide();
                    },
                    clear:function(){
                        $("#ks_level1").find('.active').removeClass('active').removeClass('color');
                        $("#ks_level2").find('.active').removeClass('active').removeClass('color');
                        $("#ks_level2").find('.div_kz_ks_level2').hide();
                        $("#ks_level3").html('');
                        $("#div_ks_tips").html('<b class="cko_wrblue">您选择的科室：</b>');
                        $('.cho_bqc').prop('checked','');
                    },
                    get_disease:function(id){
                        $.ajax({
                            type: "POST",
                            url: "/asking/diseases",
                            dataType: 'json',
                            data: "id=" + id,
                            success: function (data) {
                                var dd = '';
                                var kk = 0;
                                $.each(data, function (i, n) {
                                    var p_data_id = i;
                                    dd += '<div class="chokstree chosame mTop12" id="ks_'+p_data_id+'" style="display:none;"><h2>相关疾病</h2><div class="kstw_a  mTop12">';
                                    $.each(n, function (k, v) {
                                        var data_id = v["id"];
                                        var data_name = v['name'];
                                        dd += '<a class="" id="ks_' +data_id+ '" data-id="' +data_id+ '"  data-name="' + data_name + '">' + data_name+ '</a>';
                                    });
                                    dd += '</div></div>';
                                    kk++;
                                });
                                $(".bigTre").empty().append(dd);
                                
                                $('#ks_level3').find('a').on('click',function () {
                                    $('#ks_level3').find('a').removeClass('active');
                                    $('#ks_level3').find('a').removeClass('color');
                                    $(this).addClass("color");
                                    $(this).addClass('active');
                                    jp_keshi.set_ks_tips();
                                });
                            }
                        });
                    }
                }
                
                
                $(function(){
                    $("#btn_submit_question").click(function(){
                        jp_qas.save();
                    });
                    $(".css_txt").keyup(function () {
                        jp_helper.chgRemark($(this));
                    });
                    
                    $(".asktex_b,.asktex_d").focus(function () {
                        $(this).parent().addClass("focus");
                    }).blur(function () {
                        $(this).parent().removeClass("focus");
                    });
                    
                    //选择年龄
                    $('.ksui').click(function () {
                        $(this).next().toggle();
                    });
                    $('.ageLx a').click(function () {
                        var age_unit = $(this).attr("data-id");
                        $('.ksui').html($(this).html());
                        $("[data-field='age_unit']").val(age_unit)
                        $(this).parent().hide();
                    });
                    //选择科室
                    $(".quit_writ").focus(function(){
                        $(this).blur();
                        $('.ks_show').click();
                    });
                    $('.ks_show').click(function () {
                        jp_keshi.show_level_fst();
                    });
                    
                    $(".kstw_a  a").click(function () {
                        $(this).addClass("color").siblings().removeClass();
                    });
                    
                    $('.xlerr a,.cho_confirm').click(function () {
                        jp_keshi.set_ks_tips();
                        jp_keshi.hide();
                    });
                    
                    $('#ks_level1').find('a').on('click',function () {
                        $('#ks_level1,#ks_level2,#ks_level3').find('a').removeClass('active');
                        $(this).addClass('active');
                        $('.chokstwo').hide().eq($(this).index()).show();
                        
                        var data_id = $(this).attr("data-id");
                        jp_keshi.set_ks_tips();
                        jp_keshi.get_disease(data_id);
                    });
                    
                    $('#ks_level2').find('a').on('click',function () {
                        $('#ks_level2,#ks_level3').find('a').removeClass('active');
                        $(this).addClass('active');
                        $('.chokstree').hide().eq($(this).index()).show();
                        jp_keshi.set_ks_tips();
                    });
                    
                    <?php if($this->classid==0) { ?>
                        $(".hr_rig01 ul li").mouseover(function(){
                            $(this).addClass("on").siblings().removeClass("on");
                            $(".hr_left01 dl").hide()
                            $(".hr_left01 dl:eq("+$(this).index()+")").show()
                        });
                    <?php } ?>
//                    jp_helper.refresh_code();
                    
                });
    

            </script>
    </body>   
</html>
<?php
//    $cache_data = ob_get_contents();
//    QLib_Cache_Client::setPageCache('pages', $cache_key, $cache_data, 24);
//    ob_flush();
//}
?>