<!DOCTYPE html PUBLIC "-//W3C//h3D XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/h3D/xhtml1-transitional.h3d">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<link rel="stylesheet" type="text/css" href="/images_ask/css/rbgm.css"/>
	<link rel="stylesheet" type="text/css" href="/images_ask/css/ask.css"/>
	<title>module</title>
	<style type="text/css" media="screen">
	html,body,table{height:100%;width:100%;}
	.tmod-01{vertical-align:middle;margin:0 auto;position:relative;}
	.tmod-02{width:300px;}	
	.c_b_s_14{color:#0a2777!important;text-decoration:underline;}
	.t_center{zoom:1;}
	
	.tmod-01 .t-content{position:relative;}
	.tmod-01 .top{overflow:hidden;*zoom:1;position:absolute;top:0;left:0;width:100%;}
	</style>
</head>

<body>
	<table>
		<tr>
			<td>
				<div class="mod tmod-01">
					<h2 class="t_center h2">欢迎您成为久久健康大众会员</h2>
					<span class="close"><a href="/"><img src="/images_ask/images/ticon_2.png" style="cursor:pointer"/></a></span>
					<div class="t-content">
						<span class="top"><span class="tl"></span><span class="tr"></span></span>
						<div class="inner t_center  t_alt">
							<h3 class="t_center h2 t_alt">注贺您成为久久健康社区会员，并获赠50积分</h3>
							<!--<p style="text-align:center;"><a href="http://www.betzc.com/member/reggive2yuan/www9939.html" style="font-size:14px; font-weight:bold; color:#b60000;">*点此进入免费领取彩金页面*</a></p>-->
							<ul class="concern t_center t_alt">
								<li><span><a href="/Ask/" target="_blank">我要提问</a></span>
									<p class="c_b_s_14">解决我的健康疑惑</p>
									<p>悬赏积分，健康疑虑</p>
									<p>询问为先，获得解答</p>
								</li><li><span><a href="<?=HOME_9939_URL?>user/do/do/edit/" target="_blank">完善个人资料</a></span>
									<p class="c_b_s_14">走入健康直通车</p>
									<p>给专家更多提示</p>
									<p>让医师回答更全面</p>
								</li><li><span><a href="<?=HOME_9939_URL?>user/do/do/edithealth/" target="_blank">健康档案</a></span>
									<p class="c_b_s_14">随时掌握自己的健康状况</p>
									<p>久久健康专家将对您所</p>
									<p>填写的资料给予健康指导</p>
								</li>
							</ul>
						</div>
						<span class="bottom"><span class="bl"></span><span class="br"></span></span>
					</div>
				</div>
			</td>
		</tr>
	</table>
</body>
</html>
