<!DOCTYPE html PUBLIC "-//W3C//h3D XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/h3D/xhtml1-transitional.h3d">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<link rel="stylesheet" type="text/css" href="/images_ask/css/rbgm.css"/>
<link rel="stylesheet" type="text/css" href="/images_ask/css/ask.css"/>
	<title>module</title>
<style type="text/css" media="screen">
.tmod-02{width:300px;}	
</style>
</head>

<body>
<div class="mod tmod-01" style="display: block; position: absolute; left: 50%; top: 50%; margin-left: -280px; margin-top: -159px; z-index: 1001;">
	<h2 class="t_center h2">
		欢迎您成为久久健康医生会员
	</h2>
	<span class="close"><a href="/"><img src="/images_ask/images/ticon_2.png" style="cursor:pointer"/></a></span>
	<div class="t-content">
		<span class="top"><span class="tl"></span><span class="tr"></span></span>
		<div class="inner t_center  t_alt">
			<h3 class="t_center h2 t_alt">注贺您成为久久健康社区会员，并获赠100积分</h3>
			<ul class="concern t_center t_alt">
				<li><span><a href="/classid/0" target="_blank">我要回答</a></span>
					<p>解答患者健康疑虑</p>
					<p>获得积分，换取奖品</p>
					</li><li><span><a href="<?=HOME_9939_URL?>user/do/do/edit" target="_blank">完善个人资料</a></span>
					<p>展现名医风采</p>
					<p>让您更有名气</p>
					</li><li><span><a href="<?=DOCTOR_URL?>/" target="_blank">聚医堂</a></span>
					<p>数万专家交流</p>
					<p>与医友共探医学经验</p>
				</li>
			</ul>
		</div>
		<span class="bottom"><span class="bl"></span><span class="br"></span></span>
	</div>
</div>
</body>
</html>
