<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=7">
<title>恭喜您完成邮箱验证</title>
<link href="<?php echo HOME_9939_URL;?>images_home/style/init.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOME_9939_URL;?>images_home/style/home.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOME_9939_URL;?>images_home/style/jcy.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOME_9939_URL;?>images_home/style/tContent.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOME_9939_URL;?>images_home/style/hd.css" rel="stylesheet" type="text/css" />
<link href="<?php echo HOME_9939_URL;?>images_buluo/style/tContent.css" rel="stylesheet" type="text/css" />

</head>
<body>

<div id="doc" class="w950">

  <div id="bd" class="tMarginLg">
    <div class="g-s4m0">
      <div class="col-m">
        <div class="m-wrap zh-mwrap" style="border: 0px solid #E6E6E6;">
          
             
<div class="mail-mod-f">
               
</div>


<div class="mail-ok-f">
<div class="hd">恭喜您完成邮箱验证</div>
                <div class="bd"><ul><li>恭喜，您已完成邮箱注册。可随时进行提问、讨论<br />
现在您可以：</li>
                 <li> <a href="<?php echo ASK_URL;?>Asking/index/kw/" class="mail-btn"><span>立刻提问</span></a>   
                  <a href="<?php echo HOME_9939_URL;?>user" class="mail-btn"><span>回到个人中心</span></a> 
                  <a href="http://www.9939.com/" class="mail-btn"><span>前往久久健康</span></a> 
                  <a href="http://www.go9939.com/" class="mail-btn"><span>前往健康商城</span></a>      </li></ul></div>
</div>


             
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>