<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/images_ask/css/r.css" rel="stylesheet" type="text/css" />
<link href="/images_ask/css/m.css" rel="stylesheet" type="text/css" />
<link href="/images_ask/css/b.css" rel="stylesheet" type="text/css" />
<link href="/images_ask/css/g.css" rel="stylesheet" type="text/css" />
<link href="/images_ask/css/index.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="/images_ask/css/rbgm.css"/>
<link rel="stylesheet" type="text/css" href="/images_ask/css/ask.css"/>
<link rel="stylesheet" type="text/css" href="/images_ask/css/ask_index.css"/>
<title>会员注册-第二步</title>
<script type="text/javascript" src="/images_ask/js/jquery.tab.js"></script>
<script type="text/javascript">
$(function(){
$(document).jTab({
 menutag:".hd li"
});
});

function getPages(url){
		var html = '';
		jQuery.ajax({
			url : url+'&src=JQ',
			dataType:"json",
			cache:false,
			success:function(data){
				jQuery('#page_'+data.status+'a').html(data.pagehtml);
				jQuery('#page_'+data.status+'b').html(data.pagehtml);
				jQuery.each(data.aList,function(i){
					if(data.aList[i].content==null)data.aList[i].content='';
					html+='<dl><dt><span>'+data.aList[i].ctime+'<a href=\"#\">'+data.aList[i].username+'</a></span><strong class=\"false\"><a href=\"/ask/show/?id='+data.aList[i].id+'\">'+data.aList[i].title+'</a></strong></dt><dd><p class=\"info\"><em>悬赏分：'+data.aList[i].point+'</em> - 离问题结束还有 '+data.aList[i].endtime+'</p><p class=\"des\">'+data.aList[i].content+'</p></dd></dl>';
				});
				jQuery('#list'+data.status).html(html);
			}
		});
	}
	
</script>
</head>
<body>

<div id="doc" class="w970">
  <div id="hd"><?php require(APP_ROOT."/header195.shtml");?> </div>
  <div id="bd" class="d-mod">
    <div class="d-box1-hd"></div>
    <div class="d-box1-bd">
      <div class="hd"></div>
      <div class="bd">
        <div class="d-grid l-fix">
          <div class="col-m">
            <div class="m-wrap">
              <div class="d-box2">
                <div class="d-box2-hd">
                  <h4><a href="#">&gt;&gt;<span>医生基本信息</span></a></h4>
                </div>
                <form id="fm" action="" method="POST">
                <div class="d-2-box2">
                  <p>
                    <label>真实姓名：</label>
                    <input  type="hidden" name="firstInfo" value='<?=serialize($this->firstInfo)?>'/>
                    <input id="rname"  type="text" name="trueName" class="trueName"/>
                    <br />
                    <span class="btx"> * 必填！医生身份核实基于真实姓名。</span> </p>
                  <p>
                    <label>就职医院：</label>
                    <input  id="hos" type="text" name="hos" class="jzyy"/>
                    <br />
                    <span class="btx"> * 必填！请正确填写全称。如：中国人民解放军总医院。</span> </p>
                  <p>
                    <label>所在科室：</label>
                    <input id="keshi"  type="text" name="keshi" class="szks"/>
                    <br />
                    <span class="btx"> * 必填！</span> </p>
                    <p class="imgInfo">
                  <a href="#" onclick="checkfm();"><img  src="/images/next-btn.gif"/></a></p> </div>
                    </form>
              </div>
              
            </div>
          </div>
          <div class="col-e ">
            <div class="d-box3">
              <div class="d-box3-hd">
                <h3>简便注册，半分钟达成！</h3>
              </div>
              <div class="d-box3-bd">
                <p>第1步填写真实姓名和医院</p>
                <p>第2步留下联系方式</p>
                <p class="noborder">第3步完成注册</p>
              </div>
              <div class="d-box3-ft">
                <p class="lxwm">若您对我们的服务有任何疑问 请及时联系我们</p>
                <p class="telInfo"><span class="tel1"><strong>010-12345678</strong></span> <span><strong>400-123-9939</strong></span></p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="ft"></div>
    </div>
    <div class="d-box1-ft"><a style="color: #1F376D;"  href="http://home.9939.com/">家园</a> | <a style="color: #1F376D;"  href="http://home.9939.com/buluo/">部落</a> | <a style="color: #1F376D;"  href="http://ask.9939.com/">问答</a></div>
  </div>
 <?php require(APP_ROOT."/footer.html");?>
</div>
<script>
function checkfm(){
	var fm=document.getElementById('fm')
	var rname=document.getElementById('rname').value;
	var hos=document.getElementById('hos').value;
	var keshi=document.getElementById('keshi').value;
	fm.action="<?=$this->tzurl?>";
    
    if(!rname){
        alert('请填写真实姓名!');	
    }else if(!hos){
    	alert('请填写所在医院!');
    }else if(!keshi){
    	alert('请填写所在科室!');
    }else{
    	fm.submit();
    }
}
</script>