
<style>
.d-box1-bd .bd { background:url(http://ask.9939.com/images/bd-bg.gif) repeat-y; }
.d-grid .m-wrap { margin-right:334px; }
.d-grid .col-e { width:334px; margin-left:-334px; }
.d-box1-ft { height:41px; font-size:12px; line-height:20px; color:#ffffd5; text-align:center; padding-top:15px; }
.d-box1-ft a { color:#ffffd5; margin:0 7px; }
/*注册成功*/
.d-box2 .d-box2-hd h4 { font-size:14px; line-height:20px; padding-left:33px; padding-top:6px; }
.d-box2 .d-box2-hd h4 a { color:#2b6e88; }
.d-box2 .d-box2-hd h4 span { padding-left:6px; }
.d-box2 .d-box2-bd { padding:75px 0 53px 77px; width:478px; }
.d-box2 .d-box2-bd .gx-Info { font-family:"微软雅黑", "黑体"; font-size:32px; line-height:21.86px; color:#c20c00; }
.d-box2 .d-box2-bd .userName { font-size:14px; line-height:20px; color:#333333; padding:14px 0; }
.d-box2 .d-box2-bd .userName a { color:#2b6e88; text-decoration:underline; }
.d-box2 .d-box2-bd .userName .grInfo { padding-right:30px; }
.d-box2 .d-box2-bd .yqts { font-size:12px; line-height:20px; color:#2b6e88; padding-top:10px; padding-bottom:20px; }
.d-box2 .d-box2-bd .yqts span { float:left; }
.d-box2 .d-box2-bd .yqts .yqts-Info { padding-left:6px; width:466px; }
.d-box2 .d-box2-bd .youdo { border:1px dashed #2b6e88; font-size:14px; line-height:20px; color:#333333; padding:17px 0 42px 22px; background:#FFFFFF; }
.d-box2 .d-box2-bd .youdo li { font-size:14px; line-height:24px; }
.d-box2 .d-box2-bd .youdo li a { color:#2b6e88; }
/*右侧简便注册半分钟达成*/
.d-box3 .d-box3-hd, .d-box3 .d-box3-ft { padding-left:27px; }
.d-box3 .d-box3-bd { margin-left:27px; margin-right:40px; }
.d-box3 .d-box3-hd h3 { font-family:"微软雅黑", "黑体"; font-size:26px; line-height:24px; color:#5f8d9a; padding-top:20px; padding-bottom:10px; font-weight:normal; }
.d-box3 .d-box3-bd { font-family:"微软雅黑", "黑体"; font-size:18px; line-height:18px; color:#5f8d9a; }
.d-box3 .d-box3-bd p { border-bottom:1px dashed #5f8d9a; padding:10px 0; }
.d-box3 .d-box3-bd .noborder { border-bottom:0; padding-bottom:10x; }
.d-box3 .d-box3-ft { width: 280px;margin-left:10px; margin-right:10px; padding-left:27px; border-top:1px dashed #5f8d9a; padding-top:5px;}
.d-box3 .d-box3-ft .lxwm { font-size:12px; line-height:18px; color:#5f8d9a; }
.d-box3 .d-box3-ft .telInfo { background:url(http://ask.9939.com/images/tel-icion.gif) no-repeat; font-family:"Arial", "Helvetica", "sans-serif"; font-size:14px; line-height:18px; color:#5f8d9a; }
.d-box3 .d-box3-ft .telInfo .tel1 { padding-left:29px; margin-right:16px; }
/*3*/
.d-box2 .d-3-box2 { padding:28px 47px 0 46px; }
.d-box2 .d-3-qrInfo { border:1px dashed #2b6e88; }
.d-box2 .d-3-qrInfo dd { padding-left:14px; }
.d-box2 .d-3-box2 .d-3-qrInfo .d-3-wbg { background:#FFFFFF; }
.d-box2 .d-3-box2 .d-3-qrInfo .d-3-sm1 { font-size:14px; line-height:20px; color:#333333; padding-top:14px; }
.d-box2 .d-3-box2 .d-3-qrInfo .d-3-xxInfo { font-size:14px; line-height:20px; color:#2b6e88; padding:19px 0 19px 30px; }
.d-box2 .d-3-box2 .d-3-qrInfo .d-3-xxInfo a { color:#2b6e88; }
.d-box2 .d-3-box2 .d-3-qrInfo .d-3-sm2 { font-size:12px; line-height:16px; color:#2b6e88; padding:8px 0 8px 14px; }
.d-box2 .d-3-box2 .d-3-sm3 { font-size:12px; line-height:20px; color:#2b6e88; padding-top:31px; }
.d-box2 .d-3-box2 .d-3-tel { padding-top:5px; }
.d-box2 .d-3-box2 .d-3-tel dt { float:left; font-size:14px; line-height:27px; color:#333333; width:70px; height:36px; }
.d-box2 .d-3-box2 .d-3-tel dd { float:left; font-size:12px; line-height:20px; color:#c20c00; width:467px; }
.d-box2 .d-3-box2 .d-3-tel span { float:left; }
.d-box2 .d-3-box2 .d-3-tel .btx { padding-left:10px; width:402px; }
.d-box2 .d-3-box2 .d-3-tel input { height:27px; }
.d-box2 .d-3-box2 .d-3-tel .qh { width:57px; }
.d-box2 .d-3-box2 .d-3-tel .dwdh { width:161px; }
.d-box2 .d-3-box2 .d-3-tel .phone { width:223px; }
.d-box2 .d-3-box2 .imgInfo { padding:15px 0 20px 70px; }
/*2*/
.d-box2 .d-2-box2 { padding: 68px 0 158px 75px; }
.d-box2 .d-2-box2 p { padding: 2px 0; }
.d-box2 .d-2-box2 label { font-size:14px; line-height:27px; color:#333333; }
.d-box2 .d-2-box2 input { height:19px; width:223px; }
.d-box2 .d-2-box2 .btx { font-size:12px; line-height:20px; color:#c20c00; padding-left:70px; }
.d-box2 .d-2-box2 .imgInfo { padding:18px 0 0 72px }
.d-box3 p {
    color: #2B6E88;
    font-family: "微软雅黑","黑体";
    font-size: 18px;
    line-height: 18px;
    width: 290px;
}
</style>
<script type="text/javascript">
</script>
        <div class="d-grid l-fix">
          <div class="col-m">
            <div class="m-wrap">
              <div class="d-box2">
                <div class="d-box2-hd">
                  <h4><a href="#">&gt;&gt;<span>会员注册完成</span></a></h4>
                </div>
                <div class="d-box2-bd">
                  <p class="gx-Info">恭喜，注册成功！</p>
                  <p class="userName"> 登录管理的用户名是<strong><a href="#"><?=$this->info['username'] ? $this->info['username'] : $_COOKIE['member_username']?></a></strong></p>
                  <p class="yqts l-fix">
                  <?php if(!$this->info['uType']){?>
                  <span>*</span><span class="yqts-Info">友情提示：久久管理员将在3个工作日内和您联系核实您的身份是否真实，超过3日未反馈
                    或认定非注册医生本人，管理员将取消您的此次注册，以免其他用户错误注册。敬请等候 
                    谢谢!</span>
                    <?php }else{?>
                    <span>*</span><span class="yqts-Info">您已经成为久久会员！祝您健康！</span>
                    <?php } ?>
                    </p>
                  <dl class="youdo">
                    <dd>您现在可以：</dd>
                    <dd>
                      <ul>
                        <!--<li><a href="http://home.9939.com/user/do/do/edit">修改/完善职称、擅长和介绍>></a></li>-->
						<li><a href="http://home.9939.com/user">登录空间&gt;&gt;</a></li>
                        <li><a href="http://www.go9939.com" target="_blank">逛逛健康商城&gt;&gt;</a></li>
                        <li><a href="http://ask.9939.com/">参与问答，解决病患疑难&gt;&gt;</a></li>
                      </ul>
                    </dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>
          <div class="col-e ">
            <div class="d-box3">
              <div class="d-box3-hd">
                <h3>简便注册，半分钟达成！</h3>
              </div>
              <div class="d-box3-bd">
                <p>第1步填写真实姓名和医院</p>
                <p>第2步留下联系方式</p>
                <p class="noborder">第3步完成注册</p>
              </div>
			  <!-- 广告开始 -->
			  <div style="width:300px; height:250px; background:#FFFFFF; margin-left:12px;">
			  <a href="http://www.go9939.com/topic/34/"><img src="/9939/images/360X300shangjie.jpg" width="300" height="250" /></a>
			  </div>			  
			  <!-- 广告结束 -->
              <div class="d-box3-ft">
                <p class="lxwm">若您对我们的服务有任何疑问 请及时联系我们</p>
                <p class="telInfo"><span class="tel1"><strong>010-58359999-9755</strong></span></p>
              </div>
            </div>
          </div>
        </div>