<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>经验分享_健康经验分享_久久问医_久久健康网</title>
        <meta name="keywords" content="经验分享,健康经验分享" />
        <meta name="description" content="久久健康经验是帮助网友找到实际生活中有关健康方面怎么办、怎么做一类问题的可借鉴经验，聚集了就医看病、疾病管理、疾病预防、生活保健等健康方面的经验，找健康经验就上久久问医。" />
        <link rel="canonical" href="http://wapask.9939.com/jingyan/" >
        <link rel="stylesheet" type="text/css" href="/ask_details/css/main.css"/>
        <link rel="stylesheet" type="text/css" href="/ask_details/css/list.css"/>
        <script type="text/javascript" src="/ask_details/js/jquery-1.10.2.min.js"></script>
        <script type="text/javascript" src="/ask_details/js/scrollbar_exp.js"></script>
        <script type="text/javascript" src="/ask_details/js/gundong_exp.js"></script>
        <script type="text/javascript" src="/ask_details/js/detail.js"></script>
    </head>
    <base target="_blank">
    <body>
         <!-- 头部开始 -->   
        <!--#include virtual="/include/exp/exp_header.html"-->  
        <!-- 头部结束 -->
        <div class="banner"><div><a href="http://ask.9939.com/jingyan/shareing/share/">马上<br/>分享</a></div></div>
        <div class="content tohep">
            <h2 class="etotal"><em></em><span class="spe_01">经验分享</span><span class="spe_02">共收录<b>237256</b>条健康经验</span></h2>
            <ul class="regula">
                <?php $plates = $this->plates;?>
                <li><a href="<?php echo $plates['0']['url']?>"><div class="reg_01"></div><span>常见疾病</span></a></li>
                <li><a href="<?php echo $plates['1']['url']?>"><div class="reg_02"></div><span>生活保健</span></a></li>
                <li><a href="<?php echo $plates['2']['url']?>"><div class="reg_03"></div><span>两性健康</span></a></li>
                <li><a href="<?php echo $plates['3']['url']?>"><div class="reg_04"></div><span>整形美容</span></a></li>
            </ul>

        </div>

        <!--底部 开始-->
        <!--#include virtual="/include/exp/exp_footer.html"-->  
        <!-- 底部 结束 -->
    </body>
</html>
