<?php
/**
 * 积分不足提示
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>兑换失败！</title>
<link rel="stylesheet" type="text/css" href="<?=ASK_URL?>style/huodong/lf_ok6.css">
</head>

<body>
<div class="jubao_doc">
  <div class="jubao_tit"><span class="red">兑换失败！</span><br /><span class="hei">您的积分不够，请去回答问题赚取积分！</span></div>
  <div class="btn"><span><a href="http://ask.9939.com/asking/index/?backurl=<?=urldecode("http://ask.9939.com/huodong/index")?>">去提问</a></span><span><a href="javascript:void(0)" onclick="javascript:history.back();">返&nbsp;&nbsp;回</a></span></div>
</div>
</body>
</html>
