<?php
/**
 * 所有获奖用户
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>获奖用户列表</title>
<link target="_blank" href="<?=ASK_URL?>css/r.css" rel="stylesheet" type="text/css" />
<link target="_blank" href="<?=ASK_URL?>style/huodong/index.css" rel="stylesheet" type="text/css" />
<link target="_blank" href="<?=ASK_URL?>css/zandan.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" href="<?=ASK_URL?>images_ask/css/ask.css">
<script type='text/javascript' src="<?=ASK_URL?>Js/jquery-min.js"></script>

<script type="text/javascript">
	function dologin(){
		var username = $('#username').val();
		var password = $('#password').val();
		if(username.length==0||password.length==0){
			alert("用户名或密码错误！");
			return false;
		}   
		jQuery.getJSON("http://home.9939.com/buluo/index/do/login/?username="+username+"&password="+password+"&format=json&jsoncallback=?",function(data){
			if(data!='type0'){
					o = eval( "(" + data + ")" );
					$("#login").html('<p><span>您好</span>,<span class="col_red">'+o.username+'</span>,<span><a href="http://home.9939.com/ask/?type=1">我的提问</a></span><span><a href="#" onclick="return logout()">退出</a></span></p>');
					location.reload();
				}else if(data=='type0'){
					alert("用户名或密码错误！");
				}
		});
		return false;
	}
	function logout(){
		jQuery.getJSON("http://home.9939.com/buluo/index/do/logout/?format=json&jsoncallback=?",function(data){
				location.reload();
				return false;
		});
	}
</script>

</head>

<body>
<div class="w950">
	<div id="hd">
    	<div class="nav-top fix ">
        	<div class="login" id="login">
            	<?php 
			if($this->nickname) {
				echo '<p><span>您好</span>,<span class="col_red">'.$this->nickname.'</span>,<span><a href="http://home.9939.com/ask/?type=1">我的提问</a></span><span><a href="#" onclick="return logout()">退出</a></span></p>';
				//echo '<p>您好，<font color="col_red">'.$this->nickname.'</font>,<a href="http://home.9939.com/ask/?type=1">我的提问</a></p>';
			} else {
				echo '<form name="login"><label>用户名：</label><input type="text" class="inp" name="username" id="username"/><label>密码:</label><input name="password" id="password" type="password" class="inp" /><button class="sub-btn" type="button" onclick="dologin()">登录 </button><button class="zhuc" onclick="javascript:location.href=\'http://ask.9939.com/register?backurl='.urlencode("http://ask.9939.com/huodong/index").'\';" type="button">注册</button></form>';
			}
		?>
            </div>
            <div class="nav">
            	<a href="http://ask.9939.com/huodong/index">活动首页</a>|<a href="http://ask.9939.com/huodong/duihuan" class="on">纪念品展示</a>
            </div>
            <div class="header">
            	<img src="<?=ASK_URL?>images/huodong/header.jpg" />
            </div>
        </div>
    </div>
    <div id="bd" class="fix">
    	<div class="left">
          <div class="left01">
            <div class="tit"><h3>中奖用户</h3></div>
            <ul>
            	<?php
            		if($this->result) {
            			foreach ($this->result as $key => $val) {
            				//echo '<li><span class="rigli">'.$val['name'].'</span>..........................................<span class="leftli">'.$val['jiang'].'</span></li>';
            				echo '<li><span class="rigli">'.$val['jiang'].'</span><span class="leftli">'.$val['name'].'</span></li>';
            				
            			}
            		}
            	?>
              
            </ul>
            <p>
            	
            		<?php
            				//分页
            				if($this->pageCount>1) {
            					//首页
            					echo '<span class="no"><a href="http://ask.9939.com/huodong/huojiang/"><img src="'.ASK_URL.'images/huodong/btnleft.gif"/></a></span>';
            					
            					//上一页
            					if($this->page==1) {
            						echo '<span class="no">上一页</span>';
            					} else {
            						$page = $this->page-1;
            						echo '<span class="no"><a href="http://ask.9939.com/huodong/huojiang/page/'.$page.'">上一页</a></span>';
            					}
            					
            					//页数
            					for ($i=1; $i <= $this->pageCount; $i++) { 
            						if($i==$this->page) {
            							echo '<span class="on">';
            						} else {
            							echo '<span>';
            						}
            						echo '<a href="http://ask.9939.com/huodong/huojiang/page/'.$i.'." >'.$i.'</a></span>';
            					}
            					
            					//下一页
            					if($this->page == $this->pageCount) {
            						echo '<span class="no">下一页</span>';
            					} else {
            						$page = $this->page+1;
            						echo '<span class="no"><a href="http://ask.9939.com/huodong/huojiang/page/'.$page.'">下一页</a></span>';
            					}
            					
            					//尾页
            					echo '<span class="no"><a href="http://ask.9939.com/huodong/huojiang/page/'.$this->pageCount.'"><img src="'.ASK_URL.'images/huodong/btnrig.gif"/></a></span>';
            					
            				}
            		?>
            		
            	</p>
          </div>
        </div>
        <div class="right">
          <div class="rig01">
            <div class="top"></div>
            <div class="mid">
              <p>活动对象：<br />网站全体普通会员<br />活动时间：<br />从即日起至2010年10月9号<br />注明：<br />活动免邮费</p>
              <div class="qq">活动QQ</div>
            </div>
            <div class="bot"></div>
          </div>
        </div>
    </div>
    <div id="ft">
    	<div class="ft-nav" style="margin-top:10px;"> 
	<a href="http://www.9939.com/Company/wzjj.htm">网站简介</a>|<a href="http://www.9939.com/webmap_0_1.html">网站地图</a>|<a href="/map/">问答地图</a>|<a href="http://jb.9939.com/map.php">疾病地图</a>|<a href="http://www.9939.com/Company/wzjj.htm?tag=5">招聘信息</a>|<a href="http://www.9939.com/sitemap/">网站导航</a>|<a href="http://www.9939.com/Company/wzjj.htm?tag=4">友情链接</a>|<a href="http://www.9939.com/Company/wzjj.htm?tag=4">媒体报道</a>|<a href="mailto:jianghy@2008.shou.com">意见反馈</a>|<a href="mailto:jianghy@2008.shou.com">网上投稿</a>|<a href="http://www.9939.com/Company/wzjj.htm?tag=7">服务条款</a>|<a href="#" onclick="setHomePage(this)" target="_self">设为首页</a>|<a href="#" onclick="addfavorite()" target="_self">加入书签</a> 
	</div> 
	<div class="copyright"> 
		Copyright &copy; 2000-2009　WWW.9939.com　版权所有 玖玖叁玖网络技术(北京)有限公司 <br />特别声明：本站信息仅供参考　不能作为诊断及医疗的依据　本站如有转载或引用文章涉及版权问题请速与我们联系
	</div> 
    </div>
</div>
<div style="overflow: hidden; display: none; height: 0px;">
<script type="text/javascript" src="http://js.tongji.linezing.com/1388846/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/1388846/tongji.gif"/></a></noscript>
</div>
</body>
</html>
