<?php
/**
 * 兑换成功页面
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>兑换成功！</title>
<link rel="stylesheet" type="text/css" href="<?=ASK_URL?>style/huodong/lf_ok6.css">
</head>

<body>
<div class="jubao_doc">
  <div class="jubao_tit"><span class="red">兑换成功，请等待客服和您联系！</span><br /><span class="hei">你还有<?=$this->point?>积分，请选择</span></div>
  <div class="btn"><span><a href="http://ask.9939.com/huodong/duihuan/">继续兑换</a></span><span><a href="http://ask.9939.com/huodong/index/">砸&nbsp;&nbsp;蛋</a></span></div>
</div>
		
			
        
        
       
</body>
</html>
