<?php
/**
 * 已经兑换
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>兑换失败！</title>
<link rel="stylesheet" type="text/css" href="<?=ASK_URL?>style/huodong/lf_ok6.css">
</head>

<body>
<div class="jubao_doc">
  <div class="jubao_tit"><span class="red">兑换失败！</span><br /><span class="hei">本书已被兑换，请兑换其他图书！</span></div>
  <div class="btn"><span><a href="http://ask.9939.com/huodong/duihuan">确定</a></span></div>
</div>
</body>
</html>
